services:
  uproducts-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    networks:
      - uproducts_network
    volumes:
      - .:/ecommerce/src/app # Монтируем локальные файлы
      - /ecommerce/src/app/node_modules # Исключаем node_modules из монтирования
