services:
  uproducts-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - '3001:3001'
    networks:
      - uproducts_network

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: postgres-uproducts
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - '6543:5432'
    networks:
      - uproducts_network

  redis:
    image: redis:latest
    restart: always
    container_name: redis-uproducts
    ports: 
      - "6379:6379"

    networks:
      - uproducts_network

    volumes:
      - redisdata:/data

volumes:
  dbdata:
  redisdata:

networks:
  uproducts_network:
